# @name FindAll
GET http://localhost:8080/products

###

# @name FindById
GET http://localhost:8080/products/f94c9d21-4cf3-403c-a6df-a2504b225f5a
Content-Type: application/json

###

# @name Create
POST http://localhost:8080/products
Content-Type: application/json

{
    "name":"Produto 3",
    "price": 10.99
}

###

# @name Delete
DELETE http://localhost:8080/products/1b1cde89-5939-4976-a598-724ebe701006
Content-Type: application/json

###
POST http://localhost:8080/products/f11ce3a3-1d43-4f6c-bd55-fac45981767f/sell
Content-Type: application/json

{
    "amount": 25
}