# @name FindAll
GET http://localhost:8080/products

###

# @name FindById
GET http://localhost:8080/products/9f8b9106-e019-4292-8419-84fa07a49d12
Content-Type: application/json

###

# @name Create
POST http://localhost:8080/products
Content-Type: application/json

{
    "name":"Produto 3",
    "price": 10.99
}

###

# @name Update
PUT http://localhost:8080/products/9f8b9106-e019-4292-8419-84fa07a49d124
Content-Type: application/json

{
    "name":"teclado",
    "price": 20.99
}

###

# @name IncreaseQuantity
PUT http://localhost:8080/products/increase-quantity/9f8b9106-e019-4292-8419-84fa07a49d12
Content-Type: application/json

{
    "quantity":10
}

###

# @name Delete
DELETE http://localhost:8080/products/1b1cde89-5939-4976-a598-724ebe701006
Content-Type: application/json

###
POST http://localhost:8080/products/f11ce3a3-1d43-4f6c-bd55-fac45981767f/sell
Content-Type: application/json

{
    "amount": 25
}